### ISSUE TITLE
Missing LICENSE file

### ISSUE THREAD

**Issue by ozzr** [J-Zeitler/geometry-clipmaps#1]
Greetings!!
Really nice implementation.
I was wondering, under what license does this repo can be used?

**Comment by J-Zeitler** [comment]
Added licence https://github.com/J-Zeitler/geometry-clipmaps/blob/d0682fa8b3e98c4a70495be89de0280fb9b61e90/LICENSE

heads up: this repo contains (a very old version of) threejs which should also have MIT license

the entire project is very old, but I think this is what it does: https://www.youtube.com/watch?v=4D01JDwdfmI

**Comment by ozzr** [comment]
I am updating my terrain system and I found this repository. I wanted to update my previous CDLOD tiled terrain implementation with a new one that worked similar to Geometry Clipmaps but that used only one  quad, or similar to the Nested Grids but that required no heightmap fetch to morph between levels, that is when I found your code!!!! you have saved me a lot of headaches.

![editor_screenshot_2023-11-16T093837](https://github.com/J-Zeitler/geometry-clipmaps/assets/36895302/fd290815-ba21-4e99-87d1-475101817e62)

The image above is from GodotEngine 4.2


Once Again thanks for your amazing work!!!!

**Comment by J-Zeitler** [comment]
Looks great! Good that this old code can be of use :D
